### ISSUE TITLE
How to use/run this application?

### ISSUE THREAD

**Issue by amitjslearn** [julianjelfs/word-runner#1]
Please, update readme about how to use and which file to run? I don't know elm. Does this support pdf?

**Comment by julian-jelfs** [comment]
Uhhm, what brings you here? If you are looking for a genuinely useful tool then this is probably not for you. It is more of a code experiment. If you are looking to learn Elm then it's probably also not the best place to start since it is written in Elm 0.18 which is not the current version.

**Comment by amitjslearn** [comment]
> Uhhm, what brings you here? If you are looking for a genuinely useful tool then this is probably not for you. It is more of a code experiment. If you are looking to learn Elm then it's probably also not the best place to start since it is written in Elm 0.18 which is not the current version.

Okay, I tried to find an app that works for pdf [on linux] no luck so far. I think I will have to write one for myself.
